### ISSUE TITLE
Junk output when not spoke or for some junk sound.

### ISSUE THREAD

**Issue by BakingBrains** [mallorbc/whisper_mic#14]
Thanks for the Cool Repo. But I found when there is no audio the model gives junk transcription. 
Any suggestions to improve this here?

**Comment by SunnyOd** [comment]
@BakingBrains That's a known issue with a lot of AI models, called hallucination. Not much can be done about it unfortunately at this stage afaik

**Comment by BakingBrains** [comment]
Yep @SunnyOd , I knew, I thought there might be some method so that we can suppress the junk output. But thanks though👍

**Comment by mallorbc** [comment]
Perhaps some analysis could be done on the wav audio to see if its silence or not

**Comment by SunnyOd** [comment]
Hi. Has anyone managed to suppress the junk output? I keep getting "Thank you" and a couple of other phrases pop up during inactivity/silence. I've played with energy levels and that has helped some but I think there might be more mileage  with the fix below - possibly

I've found some threads where people have managed to fix it, [this one](https://github.com/openai/whisper/discussions/1488) looks to give the solution as including `--suppress_tokens` in the command when running `whisper`. Not sure how to add this flag to whisper_mic since the move to pip installation of whisper_mic. Is it worth looking into?

Thanks!
S

**Comment by MelvinGueneau** [comment]
hi ! it's possible to get more information about the context of your bug, like the program or somethings else ?Thanks Boulanger / Melvin Gueneauenvoyé : 11 août 2023 à 22:11de : SunnyOd ***@***.***>à : mallorbc/whisper_mic ***@***.***>cc : Subscribed ***@***.***>objet : Re: [mallorbc/whisper_mic] Junk output when not spoke or for some junk sound. (Issue #14) Hi. Has anyone managed to suppress the junk output? I keep getting "Thank you" and a couple of other phrases pop up during inactivity/silence. I've played with energy levels and that has helped some but I think there might be more mileage with the fix below - possiblyI've found some threads where people have managed to fix it, this one looks to give the solution as including --suppress_tokens in the command when running whisper. Not sure how to add this flag to whisper_mic since the move to pip installation of whisper_mic. Is it worth looking into?Thanks! S—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by mallorbc** [comment]
So this is due to hallucinations.   There doesn't seem to be a way to fully fix it due to the way that the model was trained.  It hallucinates when there is little to no audio so it makes something up.

I added a new flag that helps with this.

 I'm going to leave this issue open. If anyone finds a real solution, please ping me here. However, I think with the current flags that exist with the tool that you can find a configuration that  limits hallucinations.

**Comment by mallorbc** [comment]
The solution I developed has resolved the issue for me.  Please reopen if this is still an issue.
